### ISSUE TITLE
where is vectors.txt

### ISSUE THREAD

**Issue by dvzhang** [BeckySharp/OdinsonWebapp#15]

**Comment by dvzhang** [comment]
I can't find these files:
wordVectors = "vectors.txt"
nmodVectors = "./nmodVectors.txt"
in OdinsonWebapp/src/main/resources/application.conf 
thanks

**Comment by BeckySharp** [comment]
I can send them to you -- but I think you only need them for the simple UI
(which is not particularly ready)
are you trying to use that? or the regular webapp UI?
