### ISSUE TITLE
Recommend adding a license

### ISSUE THREAD

**Issue by nezda** [BeckySharp/OdinsonWebapp#21]
Recommend adding a license

(also maybe enable Discussions for the repo for piddly issues like this?)

**Comment by BeckySharp** [comment]
ok, so discussions enabled. that was easy.
I agree on the license.  At the moment I think I may be infected through deps with GPL, but not 100% sure.  I will make the changes needed to not be, though, and will then add an Apache one.  i just don't want to lie in the meantime.. though not 100% sure that no license is any better... :/ thanks for pointing this out though!

**Comment by nezda** [comment]
Understood. My understanding is the Apache license is solid although maybe there are confounding factors related to CLA / lack there of, etc.: IANAL

**Comment by BeckySharp** [comment]
note to self: move code here to resolve
