### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by AnShengqiang** [BeckySharp/OdinsonWebapp#9]
Thanks for the excellent work! 😊

I wonder if this still works (I can't run the code according to the instructions😭)?

**Comment by BeckySharp** [comment]
Thanks for the ping! It should, but clearly there's a problem :)  Let me
take a look,  what error are you getting, and at what step?
thanks!!

**Comment by AnShengqiang** [comment]
When I run `sbt webapp/run`, after download all the dependencies, the problem arises:


[error] /data/workspace/odinson-webapp/src/main/scala/org/clulab/reading/RuleBuilder.scala:142:31: not enough arguments for method apply: (name: String, label: Option[String], ruletype: String, priority: String, pattern: String)ai.lum.odinson.Rule in object Rule.
[error] Unspecified value parameter pattern.
[error]     val declarativeRule = Rule(s"$ruleName-decl", None, "event", declarative(subj, verb, obj, mods))
[error]                               ^
[error] /data/workspace/odinson-webapp/src/main/scala/org/clulab/reading/RuleBuilder.scala:143:27: not enough arguments for method apply: (name: String, label: Option[String], ruletype: String, priority: String, pattern: String)ai.lum.odinson.Rule in object Rule.
[error] Unspecified value parameter pattern.
[error]     val passiveRule = Rule(s"$ruleName-passive", None, "event", passive(subj, verb, obj, mods))
[error]                           ^
[error] /data/workspace/odinson-webapp/src/main/scala/org/clulab/reading/RuleBuilder.scala:144:38: not enough arguments for method apply: (name: String, label: Option[String], ruletype: String, priority: String, pattern: String)ai.lum.odinson.Rule in object Rule.
[error] Unspecified value parameter pattern.
[error]     val prepNominalizationRule = Rule(s"$ruleName-prepNominalization", None, "event", prepositionalNominalization(subj, verb, obj, mods))
[error]                                      ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 15 s, completed 2020-9-16 9:38:56
[INFO] [09/16/2020 09:38:56.778] [Thread-3] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook


I use scala 2.12, sbt 1.3, mac 10.13

Thanks for your help😄

**Comment by BeckySharp** [comment]
Thanks for pinging me about this! I didn't stay in sync with Odinson, I'll have a fix really soon!

**Comment by AnShengqiang** [comment]
> Thanks for pinging me about this! I didn't stay in sync with Odinson, I'll have a fix really soon!

Thanks, that would be very helpful!

**Comment by BeckySharp** [comment]
OK, I have #10 ready to go, would you like to check it out locally and see if it fixes your issue? If so I'll merge.
Note that I added instructions about the fact that I'm using a SNAPSHOT of Odinson (sorry! I hate having to do it, and will stop as soon as I can!!), do you need any help with that?

thanks again!

**Comment by AnShengqiang** [comment]
Thanks, it works! That is really helpful!😺

**Comment by BeckySharp** [comment]
Great!  hope you saw the (incomplete but evolving) Odinson documentation: http://gh.lum.ai/odinson/, there's a section on the language: http://gh.lum.ai/odinson/queries.html

As questions arise, reach out, and happy extracting!
